2017-12-15 00:30:29,617 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 00:30:29,618 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 00:30:29,618 root            INFO     Loading data (./data/cran_historical)
2017-12-15 00:30:29,635 root            INFO     Initializing genetic algorithm
2017-12-15 00:30:29,637 root            INFO     Running GA optimization
/usr/local/lib/python2.7/dist-packages/scoop/fallbacks.py:46: RuntimeWarning: SCOOP was not started properly.
Be sure to start your program with the '-m scoop' parameter. You can find further information in the documentation.
Your map call has been replaced by the builtin serial Python map().
  RuntimeWarning
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/coordinate_descent.py:466: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations
  ConvergenceWarning)
gen	nevals	avg    	std    	min    	max    
0  	50    	121.983	46.2281	32.3248	168.226
1  	24    	82.0583	38.2022	32.3248	168.226
2  	25    	51.7468	11.8009	32.3248	82.7861
3  	28    	37.1688	5.58536	32.2529	54.5296
4  	22    	33.2057	1.63285	31.2866	38.6835
5  	22    	31.7909	0.659849	30.3391	32.3818
6  	21    	30.9706	0.694487	29.8993	32.2461
7  	22    	30.3776	0.248929	30.1529	31.4709
8  	23    	30.2367	0.0752397	30.1529	30.4317
9  	29    	30.1508	0.15882  	29.5602	30.3391
10 	26    	30.0869	0.19526  	29.5602	30.2279
11 	24    	29.9591	0.306885 	29.1997	30.1565
12 	28    	29.6928	0.369245 	29.0768	30.1529
13 	23    	29.4679	0.287774 	29.0768	30.1529
14 	25    	29.2864	0.202489 	29.0768	29.6691
15 	26    	29.1564	0.135646 	29.0768	29.5602
16 	17    	29.1332	0.283578 	29.0768	31.0945
17 	25    	29.0768	0        	29.0768	29.0768
18 	22    	29.0768	0        	29.0768	29.0768
19 	25    	29.0768	0        	29.0768	29.0768
20 	24    	29.1008	0.167973 	29.0768	30.2766
2017-12-15 00:51:54,781 root            INFO     Saving the best parameters
2017-12-15 00:51:54,782 root            INFO     Done
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/coordinate_descent.py:466: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations
  ConvergenceWarning)
2017-12-15 00:51:55,675 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 00:51:55,675 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 00:51:55,676 root            INFO     Loading data (./data/cran_historical)
2017-12-15 00:51:55,693 root            INFO     Initializing genetic algorithm
2017-12-15 00:51:55,695 root            INFO     Running GA optimization
/usr/local/lib/python2.7/dist-packages/scoop/fallbacks.py:46: RuntimeWarning: SCOOP was not started properly.
Be sure to start your program with the '-m scoop' parameter. You can find further information in the documentation.
Your map call has been replaced by the builtin serial Python map().
  RuntimeWarning
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/coordinate_descent.py:466: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations
  ConvergenceWarning)
gen	nevals	avg    	std    	min  	max    
0  	50    	119.735	45.4796	31.86	168.226
1  	24    	60.1864	25.3593	31.86	124.912
2  	26    	33.642 	3.87686	30.7945	49.0136
3  	20    	31.5361	0.552314	29.9094	32.4459
4  	19    	31.0471	0.543524	29.6918	31.7786
5  	29    	30.4734	0.481009	29.5944	31.4759
6  	29    	29.9576	0.33144 	29.5944	30.7945
7  	29    	29.7031	0.0672923	29.5944	29.8875
8  	24    	29.6393	0.0571177	29.4916	29.7933
9  	25    	29.5724	0.0401433	29.4916	29.6549
10 	22    	29.5275	0.0424084	29.4598	29.5944
11 	25    	29.4966	0.0247659	29.4464	29.5686
12 	25    	29.4822	0.0151532	29.4464	29.5047
13 	23    	29.4695	0.0221821	29.3934	29.5215
14 	23    	29.4461	0.0283719	29.3934	29.5215
15 	22    	29.4139	0.0241772	29.3872	29.4683
16 	25    	29.3879	0.0138748	29.3593	29.42  
17 	25    	29.3685	0.0138388	29.3139	29.3953
18 	25    	29.3591	0.0121573	29.3139	29.3751
19 	26    	29.3419	0.0160989	29.3122	29.3657
20 	24    	29.3193	0.0160355	29.2881	29.35  
2017-12-15 01:05:44,086 root            INFO     Saving the best parameters
2017-12-15 01:05:44,087 root            INFO     Done
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:44,524 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:44,524 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:44,525 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:44,961 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:44,961 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:44,962 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:45,389 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:45,389 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:45,389 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:45,822 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:45,822 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:45,822 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:46,234 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:46,235 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:46,235 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:46,651 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:46,651 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:46,652 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:47,079 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:47,079 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:47,079 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
2017-12-15 01:05:47,506 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-15 01:05:47,507 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-15 01:05:47,507 root            INFO     Loading data (./data/cran_historical)
Traceback (most recent call last):
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 419, in load_from_text
    data = np.genfromtxt(path, dtype=None, delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cran_historical not found.
